# Generated by Django 4.0.2 on 2022-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=254)),
                ('post_date', models.DateField()),
                ('post_image', models.ImageField(upload_to='post_images/')),
                ('post_text', models.CharField(max_length=300)),
            ],
        ),
    ]
